name: database
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  db:
    runs-on: ubuntu-latest
    env:
        GITHUB_RUN_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-port: 27017